### PR TITLE
French translation update

### PR DESCRIPTION
**Pull request by 11jo**
Hello @GraionDilach,

Thanks for these new and excellent components !

~I notice some cases where random treasures are placed in quick item slots.~
<details>
  <summary>Spoiler warning</summary>

Old 

</details>
<details>
  <summary>Spoiler warning</summary>

Old[/spoil]
 
</details>

~Not a big issue but I let you know !~

~**_And I'm not sure if that is due to your mod !_**~

### CODE REVIEW

**Comment by 11jo** [comment]
**_After checking, they are also there in unmodded game too, so you can forget about this report._**

**Comment by GraionDilach** [comment]
Thanks!

Which are those two monsters? A fair amount of nonjoinables do keep random treasures in BG1, I'm aware of some hobgoblins doing that. It is possible that I am just exposing them.

**Comment by 11jo** [comment]
There are from BG2 : 

- SARALEGS.cre Milice of Saradush
- UHOGRE01.cre Madulf ogre from Imnesval

I just looked randomly to understand the component before translating...

**Comment by GraionDilach** [comment]
Ohwow, yeah.

Well, that's stupid but it would be a very slippery slope to try fixing/changing this (especially at a late point of installation when other mods like SoD2BG2IU or IWDification or SCS's distribute-potions introduces random treasure which needs to be worn/used in the inventory slots to function). While the random spell scrolls in this mod were only added to the quick items to attempt not overusing the inventory slots, but with the Bag of Spilling, I probably won't break things if I let them end up in the inventory.

Lolfixer also did the "unequip items in the wrong slots" as part of it's similar component and it could lead to very inconsistent results with such random placeholder items getting unequipped. Which is why I only attempt to equip alone and leave the already-equipped stuff as-is. It ensures to not be disruptive ultimately.

**Pull request merged**
